### ISSUE TITLE
How to guarantee screenshot is taken in the right moment?

### ISSUE THREAD

**Issue by ewoks** [zawadz88/ScreenshotCapturingSample#1]
I tried your demo project and [this screenshot](https://imgur.com/a/Yjbu9qz). Seems like Screenshot is taken too late (probably not too soon cause test first need to fail screenshot to be taken).

Is there any way to control that and therefore make screenshots useful? I assume when test failed it is already too late, cause activity will be destroyed and it happens like on a screenshot. What was your experience with it @zawadz88 ? tnx

**Comment by zawadz88** [comment]
Hi,
It looks to me that on the device you're testing animations are enabled (Activity looks like it's just appearing). Have you tried disabling them?
You're usually better off without them anyway - see first part of https://link.medium.com/Vmcf0ZcITW

**Comment by ewoks** [comment]
Good point, indeed that was the problem 👍 We can close this issue.

p.s. Would it make sense to add tip for the users about animation settings to the readme.md in the project root? 
`
android {
    ...
    testOptions {  
        animationsDisabled true
    }
}
`
I could make pull request tonight if that's fine with you, just let me know. Cheers

**Comment by zawadz88** [comment]
Sounds great, thanks!
